stages:
  - build-and-test

rust-latest:
  stage: build-and-test
  only:
    - master
    - merge_requests
  image: rust:latest
  script:
    - RUSTFLAGS="--deny warnings" cargo build --verbose
    - cargo clippy -- --deny warnings
    - cargo test --verbose
    - cargo test --verbose --no-default-features
