stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - RUSTFLAGS="--deny warnings" cargo build --verbose
    - cargo test --verbose
    - cargo test --verbose --features nosimd