[workspace]

members = [
    "rsonpath",
    "simd-codegen",
    "simd-benchmarks",
    "decimal-byte-measurement",
    "rsonpath-benchmarks"
]

[profile.dev]
lto = false

[profile.release]
lto = "thin"