[package]
name = "simdpath-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
memchr = "2.4.1"

[features]
nosimd = []