#[build]
#target = "wasm32-unknown-unknown"
#
#[target.wasm32-unknown-unknown]
#linker = "rust-lld"
#rustflags = ["-C", "link-arg=--export-table"]

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]


[alias]
rsontest = "hack test -q --feature-powerset --skip default -F arbitrary -F serde --ignore-unknown-features"

[env]
RUST_BACKTRACE = "1"
